spring.application.name=employee-management-backend

spring.datasource.url=jdbc:postgresql://ajinkya-postgres.czscmg4ae1m7.eu-north-1.rds.amazonaws.com:5432/myappdb
spring.datasource.username=postgres
spring.datasource.password=Postgres12345

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true